### ISSUE TITLE
Publish a new version

### ISSUE THREAD

**Issue by gutenye** [Naerth/commander-autocompletion#19]
Hi, thank you for creating this fantastic library! I noticed that options completion has been added, but it isn’t available in the npm package yet. Would it be possible for you to publish a new version? Thank you!

**Comment by Naerth** [comment]
Hi, thanks for letting me know!
I'll look into publishing the new version with the options completion feature this week. I'll keep you posted.

**Comment by Naerth** [comment]
Hi,

Just wanted to let you know that the package has been published in version v0.0.10-rc, which includes the options completion feature!

Feel free to try it out, and let me know if everything works as expected. Once you're all set, I'll close the ticket.

Thanks again for your patience!

**Comment by gutenye** [comment]
It worked, thank you.
